# 📅 Escala Automática a partir do Google Sheets

Este notebook lê automaticamente a planilha publicada no Google Sheets (formato CSV),
mostra a escala em tabela e permite exportar para HTML para compartilhar via link.

A planilha é atualizada todos os dias às 8h — basta abrir/rodar este notebook para ver os dados mais recentes.

In [1]:
import pandas as pd

# 🔗 Link CSV publicado da sua planilha
csv_url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vTtu-b1fJg3AaYjKpcmYvdB1AaZpWGTRPr76mBxyBczreE69_A_3_NLJ4OPuGMtefWyTzl56G0oklFo/pub?output=csv"

# Lendo os dados direto do Google Sheets
df = pd.read_csv(csv_url)

df.head()

   Unnamed: 0 Unnamed: 1 Unnamed: 2   Unnamed: 3 Unnamed: 4   Unnamed: 5
0        Data   Animação   Condução        Dança   Pregação  Comunicação
1  21/01/2024      Pedro        NaN   Sofi e Ana     Deyvid          NaN
2  28/01/2024      Carla        NaN  Ana e Lopes   Pedrinho          NaN
3  04/02/2024     Deyvid        NaN  Lopes e Ana    Adriano          NaN
4  11/02/2024        NaN        NaN          NaN        NaN          NaN

## 🔍 Visualização completa da escala

In [2]:
df

     Unnamed: 0 Unnamed: 1 Unnamed: 2   Unnamed: 3 Unnamed: 4   Unnamed: 5
0          Data   Animação   Condução        Dança   Pregação  Comunicação
1    21/01/2024      Pedro        NaN   Sofi e Ana     Deyvid          NaN
2    28/01/2024      Carla        NaN  Ana e Lopes   Pedrinho          NaN
3    04/02/2024     Deyvid        NaN  Lopes e Ana    Adriano          NaN
4    11/02/2024        NaN        NaN          NaN        NaN          NaN
..          ...        ...        ...          ...        ...          ...
408  18/01/2032        NaN        NaN          NaN        NaN          NaN
409  25/01/2032        NaN        NaN          NaN        NaN          NaN
410  01/02/2032        NaN        NaN          NaN        NaN          NaN
411  08/02/2032        NaN        NaN          NaN        NaN          NaN
412  15/02/2032        NaN        NaN          NaN        NaN          NaN

[413 rows x 6 columns]

## 💾 Exportar para HTML (para virar um link/app web)

In [4]:
html_file = "escala.html"

df.to_html(html_file, index=False)

html_file

'escala.html'

Abra o arquivo HTML gerado e publique no Netlify, Vercel ou GitHub Pages para ter um link público.

Sempre que rodar este notebook, o HTML será atualizado com a escala mais recente.